---
- name: Check if `cargo` is installed
  register: __cargo_exists
  failed_when: false
  changed_when: false
  ansible.builtin.shell:
    cmd: command -v cargo

- name: Download the Rust Installer
  when: __cargo_exists.rc != 0
  ansible.builtin.get_url:
    url: "{{ rust_installer_url }}"
    dest: "{{ rust_installer_dest }}"
    mode: "{{ rust_installer_mode }}"
    force: true

- name: Run the Rust Installer
  when: __cargo_exists.rc != 0
  when: __cargo_exists is failed
  ansible.builtin.shell:
    cmd: "{{ rust_installer_dest }} -y"
