---
- name: Verify
  hosts: all
  gather_facts: false

  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Find the cargo command
      ansible.builtin.shell:
        cmd: . ~/.bashrc; command -v cargo
